services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Vankosoft\CmsBundle\Controller\GetImageController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - "@liip_imagine.binary.loader.default"
            - "@liip_imagine.filter.manager"

    Vankosoft\CmsBundle\Controller\PagesExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.repository.taxonomy'
            - '@vs_application.repository.taxon'
            - '@vs_cms.repository.pages'
            - '@vs_cms.repository.page_categories'
            - '@vs_application.repository.logentry'
            - '@vs_cms.factory.pages'
            
    Vankosoft\CmsBundle\Controller\MultiPageTocPageController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_cms.repository.multipage_toc'
            - '@vs_cms.repository.multipage_toc_page'
            - '@vs_cms.factory.multipage_toc_page'
            - '@vs_cms.repository.pages'
            - '@vs_application.repository.taxonomy'

    Vankosoft\CmsBundle\Controller\ArtgrisFileManagerController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_cms.file_manager'
    
    Vankosoft\CmsBundle\Controller\VankosoftFileManagerExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_cms.repository.file_manager'
            - '@vs_cms.repository.file_manager_file'
            - '@vs_cms.factory.file_manager_file'
            - '@vs_cms.file_manager'
