services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Vankosoft\CmsBundle\Controller\GetImageController:
        tags: ['container.service_subscriber', 'controller.service_arguments']
        autowire: true
        arguments:
            - "@liip_imagine.binary.loader.default"
            - "@liip_imagine.filter.manager"
        calls:
            - [ setContainer, [ '@service_container' ] ]

    Vankosoft\CmsBundle\Controller\PagesCategoryExtController:
        tags: ['container.service_subscriber', 'controller.service_arguments']
        autowire: true
        arguments:
            - '@translator'
            - '@vs_cms.repository.page_categories'
        calls:
            - [ setContainer, [ '@service_container' ] ]
    
    Vankosoft\CmsBundle\Controller\PagesExtController:
        tags: ['container.service_subscriber', 'controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '@vs_application.repository.taxon'
            - '@vs_cms.repository.pages'
            - '@vs_cms.repository.page_categories'
            - '@vs_application.repository.logentry'
            - '@vs_cms.factory.pages'
            - '@vs_application.repository.tags_whitelist_context'
            
    Vankosoft\CmsBundle\Controller\MultiPageTocPageController:
        tags: ['container.service_subscriber', 'controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_cms.repository.document'
            - '@vs_cms.repository.toc_page'
            - '@vs_cms.factory.toc_page'
        calls:
            - [ setContainer, [ '@service_container' ] ]

    Vankosoft\CmsBundle\Controller\ArtgrisFileManagerController:
        tags: ['container.service_subscriber', 'controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_cms.file_manager'
        calls:
            - [ setContainer, [ '@service_container' ] ]
    
    Vankosoft\CmsBundle\Controller\VankosoftFileManagerExtController:
        tags: ['container.service_subscriber', 'controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_cms.repository.file_manager'
            - '@vs_cms.repository.file_manager_file'
            - '@vs_cms.factory.file_manager_file'
            - '@vs_cms.file_manager'
        calls:
            - [ setContainer, [ '@service_container' ] ]
            
    Vankosoft\CmsBundle\Controller\SliderItemExtController:
        tags: ['container.service_subscriber', 'controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_cms.repository.slider'
            - '@vs_cms.repository.slider_item'
            - '@vs_cms.factory.slider_item'
            - '@vs_cms.file_manager'
            - '%vs_application_slider_photo_description%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
