services:
    vs_cms.resources.pages.form:
        class: Vankosoft\CmsBundle\Form\PageForm
        tags:
            - { name: form.type }
        arguments:  # '%vs_cms.pages.form.type.validation_groups%'
            - "@request_stack"
            - '%vs_cms.model.pages.class%'
            - '%vs_cms.model.page_categories.class%'
            
#     vs_cms.resources.documents.form:
#         class: Vankosoft\CmsBundle\Form\DocumentForm
#         tags:
#             - { name: form.type }
#         arguments:
#             - "@request_stack"
#             - '%vs_cms.model.documents.class%'
#             - '%vs_cms.model.multipage_toc.class%'

    vs_cms.resources.page_categories.form:
        class: Vankosoft\CmsBundle\Form\PageCategoryForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.page_categories.class%'
            - '@vs_cms.repository.page_categories'
            
    vs_cms.resources.multipage_toc.form:
        class: Vankosoft\CmsBundle\Form\MultiPageTocForm
        tags:
            - { name: form.type }
        arguments:
            - "@request_stack"
            - '%vs_cms.model.multipage_toc.class%'
            - '%vs_cms.model.multipage_toc_page.class%'
            - '%vs_cms.model.pages.class%'

    Vankosoft\CmsBundle\Form\TocPageForm:
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.multipage_toc_page.class%'
            - '%vs_cms.model.pages.class%'

    Vankosoft\CmsBundle\Form\FileManager\UploadFileForm:
        tags:
            - { name: form.type }
    
    vs_cms.resources.file_manager.form:
        class: Vankosoft\CmsBundle\Form\VankosoftFileManagerForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.file_manager.class%'
    
    vs_cms.resources.file_manager_file.form:
        class: Vankosoft\CmsBundle\Form\VankosoftFileManagerFileForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.file_manager_file.class%'
            