parameters:
    # Pages Form Options
    ##########################################################
    vs_cms.form.pages.ckeditor_uiColor: '#ffffff'
    vs_cms.form.pages.ckeditor_extraAllowedContent: '*[*]{*}(*)'
    vs_cms.form.pages.ckeditor_toolbar: devpage_toolbar
    vs_cms.form.pages.ckeditor_extraPlugins: 'font, justify, codesnippet, lightbox'
    vs_cms.form.pages.ckeditor_removeButtons: ''
    
    # TocPage Form Options
    ##########################################################
    vs_cms.form.toc_page.ckeditor_uiColor: '#ffffff'
    vs_cms.form.toc_page.ckeditor_extraAllowedContent: '*[*]{*}(*)'
    vs_cms.form.toc_page.ckeditor_toolbar: devpage_toolbar
    vs_cms.form.toc_page.ckeditor_extraPlugins: 'font, justify, codesnippet, lightbox'
    vs_cms.form.toc_page.ckeditor_removeButtons: ''

services:

    ##########################################################
    # Override Symfony Service '@form.factory' to be Public
    # Needed in PagesController to Clone and Preview Forms
    ##########################################################
    form.factory:
        class: Symfony\Component\Form\FormFactory
        arguments: ['@form.registry']
        public: true
    
    vs_cms.resources.page_categories.form:
        class: Vankosoft\CmsBundle\Form\PageCategoryForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.page_categories.class%'
            - '@vs_cms.repository.page_categories'
            - "@request_stack"
            
    vs_cms.resources.pages.form:
        class: Vankosoft\CmsBundle\Form\PageForm
        tags:
            - { name: form.type }
        arguments:  # '%vs_cms.pages.form.type.validation_groups%'
            - "@request_stack"
            - '%vs_cms.model.pages.class%'
            - '%vs_cms.model.page_categories.class%'
            
    vs_cms.resources.document_categories.form:
        class: Vankosoft\CmsBundle\Form\DocumentCategoryForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.document_categories.class%'
    
    vs_cms.resources.document.form:
        class: Vankosoft\CmsBundle\Form\DocumentForm
        tags:
            - { name: form.type }
        arguments:
            - "@request_stack"
            - '%vs_cms.model.document.class%'
            - '%vs_cms.model.document_categories.class%'
            - '%vs_cms.model.toc_page.class%'
    
    Vankosoft\CmsBundle\Form\TocPageForm:
        tags:
            - { name: form.type }
        arguments:
            - "@request_stack"
            - '%vs_cms.model.toc_page.class%'

    Vankosoft\CmsBundle\Form\FileManager\UploadFileForm:
        tags:
            - { name: form.type }
    
    vs_cms.resources.file_manager.form:
        class: Vankosoft\CmsBundle\Form\VankosoftFileManagerForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.file_manager.class%'
    
    vs_cms.resources.file_manager_file.form:
        class: Vankosoft\CmsBundle\Form\VankosoftFileManagerFileForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.file_manager_file.class%'
            