vs_cms_pages:
    resource: |
        alias: vs_cms.pages
        except: ['show']
        path: /pages
        templates: "@VSCms/Pages/Pages"
        form:
            options:
                ckeditor_toolbar: '%vs_cms.pages.ckeditor_toolbar%'
    type: sylius.resource

vs_cms_pages_show_by_id:
    path: /pages/{id}
    methods: [GET]
    defaults:
        _controller: vs_cms.controller.pages:showAction
        _sylius:
            template: "@VSCms/Pages/Pages/show.html.twig" # If you want you can use a custom template.

vs_cms_pages_show_by_slug:
    path: /pages/{slug}
    methods: [GET]
    defaults:
        _controller: vs_cms.controller.pages:showAction
        _sylius:
            template: "@VSCms/Pages/Pages/show.html.twig" # If you want you can use a custom template.
            repository:
                # If you want you can use a custom repository method.
                method: findBySlug
                arguments: [$slug] # Pass the slug from the url to the repository.

vs_cms_page_categories:
    resource: |
        alias: vs_cms.page_categories
        path: /page_categories
        templates: "@VSCms/Pages/Page_Categories"
    type: sylius.resource

# Page Action Routes
vs_cms_pages_clone:
    path: /page-actions/clone/{pageId}
    controller: Vankosoft\CmsBundle\Controller\PagesExtController::clonePage
vs_cms_pages_preview:
    path: /page-actions/preview/{pageId}/{locale}/{version}
    controller: Vankosoft\CmsBundle\Controller\PagesExtController::previewPage
    defaults:   { version: null }
vs_cms_pages_form_in_locale:
    path: /page-actions/get-form/{locale}/{pageId}
    controller: Vankosoft\CmsBundle\Controller\PagesExtController::getPageForm

# Page Categories Callbacks
vs_cms_pages_tree_combo:
    path: /json/pages-categories-{taxonomyId}/easyui-combotree
    controller: Vankosoft\CmsBundle\Controller\PagesExtController::easyuiComboTreeSource

vs_cms_pages_tree_combo_with_selected:
    path: /json/{pageId}/pages-categories-{taxonomyId}/easyui-combotree
    controller: Vankosoft\CmsBundle\Controller\PagesExtController::easyuiComboTreeWithSelectedSource

vs_cms_pages_tree_combo_with_leafs:
    path: /json/pages-categories-{taxonomyId}/easyui-combotree-with-leafs
    controller: Vankosoft\CmsBundle\Controller\PagesExtController::easyuiComboTreeWithLeafsSource
    
vs_cms_pages_tree_table:
    path: /json/pages-categories-{taxonomyId}/gtreetable
    controller: Vankosoft\CmsBundle\Controller\PagesExtController::gtreeTableSource

# Custom Routes
vs_cms_pages_categories_update_by_taxon:
    path: /json/update-pages-category-by-taxon/{taxonId}
    controller: Vankosoft\CmsBundle\Controller\PagesExtController::updateCategory_ByTaxonId
vs_cms_pages_categories_delete_by_taxon:
    path: /json/delete-pages-category-by-taxon/{taxonId}
    controller: Vankosoft\CmsBundle\Controller\PagesExtController::deleteCategory_ByTaxonId
vs_cms_pages_categories_move_by_taxon:
    path: /json/move-pages-category-by-taxon/{sourceTaxonId}-{destinationTaxonId}-{position}
    controller: Vankosoft\CmsBundle\Controller\PagesExtController::moveCategory_ByTaxonId

