vs_cms_document_categories:
    resource: |
        alias: vs_cms.document_categories
        path: /document-categories
        templates: "@VSCms/Pages/Document_Categories"
    type: sylius.resource

vs_cms_document:
    resource: |
        alias: vs_cms.document
        path: /documents
        templates: "@VSCms/Pages/Document"
    type: sylius.resource
    
vs_cms_toc_page_index:
    path: /toc-pages/{documentId}/
    methods: [GET]
    defaults:
        _controller: vs_cms.controller.toc_page:indexAction
        _sylius:
            paginate: 30
            sorting:
                score: desc
            filterable: true
            criteria:
                document: $documentId
            template: "@VSCms/Pages/TocPage/index.html.twig"
    options:
        expose: true
        
vs_cms_toc_page:
    resource: |
        alias: vs_cms.toc_page
        path: /toc-pages/{documentId}
        templates: "@VSCms/Pages/TocPage"
    type: sylius.resource
    options:
        expose: true

vs_cms_multipage_toc_page_gtreetable:
    path: /multipage_toc_{documentId}_gtreetable
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::gtreeTableSource

vs_cms_multipage_toc_page_easyui_combotree:
    path: /multipage_toc_{documentId}_easyui-combotree
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::easyuiComboTreeSource
    
vs_cms_multipage_toc_page_edit:
    path: /multipage_toc_{documentId}/toc_page_form
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::editTocPage
    
vs_cms_multipage_toc_page_handle:
    path: /multipage_toc_{documentId}/toc_page_form/handle
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::handleTocPage
