vs_cms_document_categories:
    resource: |
        alias: vs_cms.document_categories
        path: /document-categories
        templates: "@VSCms/Pages/Document_Categories"
    type: sylius.resource

vs_cms_document:
    resource: |
        alias: vs_cms.document
        path: /documents
        templates: "@VSCms/Pages/Document"
    type: sylius.resource
    
vs_cms_toc_page:
    resource: |
        alias: vs_cms.toc_page
        path: /toc-pages
        templates: "@VSCms/Pages/TocPage"
    type: sylius.resource
    

vs_cms_multipage_toc_page_gtreetable:
    path: /multipage_toc_{tocId}_gtreetable
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::gtreeTableSource

vs_cms_multipage_toc_page_easyui_combotree:
    path: /multipage_toc_{tocId}_easyui-combotree
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::easyuiComboTreeSource
    
vs_cms_multipage_toc_page_edit:
    path: /multipage_toc_{tocId}/toc_page_form
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::editTocPage
    
vs_cms_multipage_toc_page_handle:
    path: /multipage_toc_{tocId}/toc_page_form/handle
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::handleTocPage
