vs_cms_helpcenter_question:
    resource: |
        alias: vs_cms.helpcenter_question
        except: ['show']
        path: /helpcenter/questions
        templates: "@VSCms/Pages/HelpCenterQuestions"
    type: sylius.resource
    options:
        expose: true

vs_cms_helpcenter_question_index:
    path: /helpcenter/questions/
    methods: [GET]
    defaults:
        _controller: vs_cms.controller.helpcenter_question::indexAction
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                updatedAt: desc
            filterable: true
            template: "@VSCms/Pages/HelpCenterQuestions/index.html.twig"
    options:
        expose: true
        
vs_cms_quick_link:
    resource: |
        alias: vs_cms.quick_link
        except: ['show']
        path: /quick-links
        templates: "@VSCms/Pages/QuickLinks"
    type: sylius.resource
    options:
        expose: true

vs_cms_quick_link_index:
    path: /quick-links/
    methods: [GET]
    defaults:
        _controller: vs_cms.controller.quick_link::indexAction
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                updatedAt: desc
            filterable: true
            template: "@VSCms/Pages/QuickLinks/index.html.twig"
    options:
        expose: true

vs_cms_slider:
    resource: |
        alias: vs_cms.slider
        except: ['show']
        path: /sliders
        templates: "@VSCms/Pages/Sliders"
    type: sylius.resource
    options:
        expose: true

vs_cms_slider_item_index:
    path: /sliders-items/{sliderId}/
    methods: [GET]
    defaults:
        _controller: vs_cms.controller.slider_item::indexAction
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                updatedAt: desc
                score: desc
            filterable: true
            criteria:
                slider: $sliderId
            template: "@VSCms/Pages/SlidersItems/index.html.twig"
    options:
        expose: true

vs_cms_slider_item:
    resource: |
        alias: vs_cms.slider_item
        except: ['show']
        path: /sliders-items/{sliderId}
        templates: "@VSCms/Pages/SlidersItems"
        form:
            options:
                ckeditor_uiColor: '%vs_cms.form.decription_field.ckeditor_uiColor%'
                ckeditor_toolbar: '%vs_cms.form.decription_field.ckeditor_toolbar%'
                ckeditor_extraPlugins: '%vs_cms.form.decription_field.ckeditor_extraPlugins%'
                ckeditor_removeButtons: '%vs_cms.form.decription_field.ckeditor_removeButtons%'
                ckeditor_allowedContent: '%vs_cms.form.decription_field.ckeditor_allowedContent%'
                ckeditor_extraAllowedContent: '%vs_cms.form.decription_field.ckeditor_extraAllowedContent%'
    type: sylius.resource
    options:
        expose: true
        
vs_cms_slider_item_ext_sort_action:
    path: /slider-item-sort/{id}/{insertAfterId}
    controller: Vankosoft\CmsBundle\Controller\SliderItemExtController::sortAction
    options:
        expose: true

vs_cms_slider_item_ext_edit:
    path: /slider-item-edit/{sliderId}/{itemId}/{locale}
    controller: Vankosoft\CmsBundle\Controller\SliderItemExtController::editSliderItem
    defaults: { locale: '%locale%' }
    options:
        expose: true
    
vs_cms_slider_item_ext_delete:
    path: /slider-item-delete/{sliderId}/{itemId}
    controller: Vankosoft\CmsBundle\Controller\SliderItemExtController::deleteSliderItem
    options:
        expose: true


